### PR TITLE
Fixes #89 - Reverse Gamma Correction Formula

### LINKED ISSUE #89: WS2812BHueStrip, dimming issue
Hello,

Great work, liked it the first time I used it. I use the ws2812B Hue strip, and I have a small issue. with dimming the strip. It seems that full brightness is reached after around 20% when using the official hue app. In other words, there is no difference between 20% dimlevel and 100% dimlevel of the ledstrip. DId you see that occuring in your setup?

I used your WS2812 ino file on both esp01 and nodemcu.

Thanks again.

Best regards.

### PR DESCRIPTION
**Pull request by shbatm**
As discussed in Issue #89

### CODE REVIEW

**Comment by Mevel** [comment]
I tried both the Fancy and aproximation Formula. The aproximation mixed up the colors. No issues with fancy calculation. Can some one confirm?

**Comment by mariusmotea** [comment]
I test now with my ceiling lamp  that use pwm drivers with rgb leds and i need to do some photos because i don't know exactly the difference. I see the red is very powerful while green become colorless. Blue is perfect. My big problem is that at 1% i don't have any light. I believe all bulbs from market when brightness is set to 1% from application on leds they still provide minimum 3-5% of power because i have Tradfri bulbs and at 1% there is still plenty light.

**Comment by shbatm** [comment]
You may try using different exponents for different color channels.
capture
For example, to boost the green and limit the red, you could change the `2.4f` at the end of the line to `1.6f` and `3.0f`, respectively.  Not a perfect solution, but according to the Adafruit article I linked in #89, the different channels may require different correction factors.

**Comment by mariusmotea** [comment]
i will test and come back. Currently i'm very busy at my work.

**Comment by shbatm** [comment]
Updated based on additional findings from #89.  Please test and if found working I will update the remaining firmware files.

**Pull request merged**
