### PR TITLE
Update WS2812BHueStrip.ino

### PR DESCRIPTION
**Pull request by Mevel**
Added Light Name Variable in HTML`<title>` and `WiFi.hostname(light_name);` in `Setup()`

### CODE REVIEW

**Comment by mariusmotea** [comment]
i'm doing the same thing now, but hostname is not working as expected for me.

**Comment by Mevel** [comment]
this code worked for me and my AVM Fritzbox Router

**Comment by Mevel** [comment]
maybe the Position of WiFi.hostname is important? i had it before Wifimanager

**Comment by mariusmotea** [comment]
I try to figure if is because of lengh or spaces in the name. In my case i have 3 words (2 spaces). After i remove the spaces is working, before the hostname was `[]`. I will test again by inserting one space just to be sure.

**Comment by mariusmotea** [comment]
i believe the number of characters is the issue because i tried now with lower number and one space and it work.

**Comment by Mevel** [comment]
I have one space and in the Router ui it gets replaced by "-".

This might be the issue.
So maybe replace space with character.

Motea Marius <notifications@github.com> schrieb am So., 2. Sep. 2018, 14:29:

**Pull request merged**
