### PR TITLE
Travis Integration in Repo

### PR DESCRIPTION
**Pull request by schabert**
I have merged the docker build repository from github together with small modifications like the requirements.txt for external dependencies.
openssl.conf direct in repository
docker_compose file in the repository

This is important to write python tests for the source code e.g. https running?
Format is valid for apps and more like a mocked test for yeelight to not break the application.

Additional the benefit is that everyone can pull the master via docker if required.

To enable travis you have to go to travis and activated the build and set 2 variables for pushing the images to diyhue:core i can send you the environment variables that has to be set in travis via PM.

The build is currently running on my branch and pushes the changes already to
https://hub.docker.com/r/diyhue/core/tags/
diyhue/core:armhf
diyhue/core:amd64

### CODE REVIEW

**Comment by cheesemarathon** [comment]
Also @Christoph-Schabert  if you look [here](https://cloud.docker.com/swarm/diyhue/repository/docker/diyhue/core/general) and hover over the penguins next to each tag name, you will see it identifies both the amd64 images and armhf tagged images as using an amd64 architecture. So it does look like the arm images are not built correctly.

**Comment by cheesemarathon** [comment]
Ah! I have noticed you have the `docker run --rm --privileged multiarch/qemu-user-static:register` line to register QEMU in the build agent. Your base image `mielune/alpine-python3-arm` is built from `hypriot/rpi-alpine` which contains the QEMU binary so it should work. Maybe the penguin thing is just a bug?

**Comment by cheesemarathon** [comment]
Ok, ignore everything I said. The armhf image works fine on my pi3! Hue entertainment does not work though. I'm looking into it at the moment.

**Comment by cheesemarathon** [comment]
Ah I remember now. Entertainment-srv requires glibc, This is not included in alpine and was a bit of a pain to install. So I switched to a slim debian based image. However we need QEMU support. This is baked into `resin/rpi-raspbian`. Unfortunately this means larger images, around 110MiB

**Comment by Christoph-Schabert** [comment]
I have tested the build on my raspberry pi but I don't use entertains so i haven't tested it.
Pushed a new version but currently stuck at travis :-) Friday afternoon

check the build later

**Comment by cheesemarathon** [comment]
I think you will need to move from apk to apt as the package manager as the image is debian based. See my PR for your folk. I have built that PR and they work. You will need to make changes to amd64.Dockerfile as that is alpine based also.

**Comment by cheesemarathon** [comment]
@mariusmotea You happy with this? I am now. Can we merge?

**Comment by mariusmotea** [comment]
Yes.

**Pull request merged**
