### PR TITLE
	fix opposite temperature rgbcct ledstrip controller issue #42

### PR DESCRIPTION
**Pull request by kurniawan77**
this got fixed in the ESP Milight hub source. Reverting back

### CODE REVIEW

**Comment by kurniawan77** [comment]
Why closed?

**Comment by mariusmotea** [comment]
Hi
"this got fixed in the ESP Milight hub source. Reverting back" i did not understand this. It was fixed on milight hub or it still need to be fixed here. If yes, please open new pr. I close because i had conflict with new pr made yesterday by me.

**Comment by mariusmotea** [comment]
I was able to reopen this pr. Is ok now, right?

**Comment by kurniawan77** [comment]
Yes, now is ok. 
Sorry, i wasn't to clear indeed. Like you said in the issue, it was a bug in the esp milight hub. After you supported it, it got fixed in the esp milight hub, so this reverts to how it is suppose to be working.

**Pull request merged**
