### PR TITLE
feat: poll API to keep UI in sync

### PR DESCRIPTION
**Pull request by FezVrasta**
We still need to find a way to better sync the UI with the value of the slides when the user is interacting with them

I also fixed the responsivity bug

sss

### CODE REVIEW

**Comment by mariusmotea** [comment]
Thanks, i will test in 30 minutes

**Comment by mariusmotea** [comment]
Is working quite good now. The only problem is with color picker going to blue every time. According to documentation the defaultColor need to receive the color in hex string format. Setting `defaultColor={cieToRgb(selectedLight.state.xy[0],selectedLight.state.xy[1],selectedLight.state.bri)}` still do not work. I try then to setup manually the color #ff0000 and it is still not changing to red, so i believe there is a bug in the library. 
Do you know how to do `if ... else if .... else` in curly brackets as i detect a new bug with bulb color, if is non color, non ct light i need to setup a default color?

**Comment by FezVrasta** [comment]
```
if (something) {
  ...
} else if (something_else) {

}
```

**Comment by mariusmotea** [comment]
`color={cieToRgb(selectedLight.state.xy[0],selectedLight.state.xy[1],selectedLight.state.bri)}` is working in initial state, the hue slider is set on the correct color, but when i mode it to different color it return to initial one.

**Pull request merged**
