### PR TITLE
Use defines to enable static IP configuration

### PR DESCRIPTION
**Pull request by Nikfinn99**
using defines is more user friendly as the user does not have to search for the commented lines.

### CODE REVIEW

**Comment by mariusmotea** [comment]
Thanks for your contribution.

**Comment by Nikfinn99** [comment]
As next project i'm planning to create PCB Files for different lights and switches.
I'm still not 100% certain for the power supply as WS2812 LED's can draw a lot of current, but maybe a 12V 2A power supply (~3$) and a 5V 5A buck converter? This would be enough for most projects of around 130-150 LED's.

**Comment by Nikfinn99** [comment]
So far i've been using an old ATX power supply, which has been working perfectly, as it can deliver around 30A. I guess i could just put a [5.5x2.1mm DC connector](https://www.aliexpress.com/item/20PCS-5-5x2-1-DC-005-Electrical-Jack-Socket-Power-Outlet-Audio-Video-Connector/32824292092.html) on the board and then users can choose their power supply.
PCB's could also be designed to be able to choose either 12v or 5v as input. When 12v mode is active a  [buck converter](https://www.aliexpress.com/item/5V-3A-DC-DC-Step-Down-Buck-Converter-Adapter-Adjustable-DC-DC-Step-Down-Power-Supply/32907279714.html) is required for the esp and shorter LED strips.
I haven't ordered anything from Aliexpress jet, just from eBay, but most articles can be found there too.

**Comment by cheesemarathon** [comment]
@Nikfinn99 I suggest that you [join us on slack](https://slackinvite.squishedmooo.com/) and have a chat with everyone there about your PCB's. There is a channel dedicated to custom hardware!

**Pull request merged**
